import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Providers } from "./providers";
=======
>>>>>>> b58838c9e270c6a5158cbe6bf5c3ff8b9291dc9e

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Notes App",
  description: "A simple notes application built with Next.js and Redux Toolkit.",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> b58838c9e270c6a5158cbe6bf5c3ff8b9291dc9e
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
<<<<<<< HEAD
        <Providers>{children}</Providers>
=======
        {children}
>>>>>>> b58838c9e270c6a5158cbe6bf5c3ff8b9291dc9e
      </body>
    </html>
  );
}
